permissions:
  contents: read
name: CI

on:
    workflow_dispatch:
     inputs:
      branch:
        description: '选择构建的分支'
        required: true
        default: 'main'
#  push:
#    branches: [ "main" ]
#    paths-ignore:
#      - "**.md"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK 21
        uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

 #     - name: Load Google Services File
#        env:
#          DATA: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
 #       run: echo $DATA | base64 -di > app/google-services.json

#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        
      - name: Decode keystore
        run: |
          echo "${{ secrets.YOUR_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Set up keystore for signing
        run: |
          mkdir -p $HOME/.android
          mv keystore.jks $HOME/.android/keystore.jks

      - name: Build and sign APK with Gradle
        run: gradle assembleDebug
        env:
          KEYSTORE_PASSWORD: ${{ secrets.YOUR_KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.YOUR_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          HA_GITHUB_TOKEN: ${{ secrets.HA_GITHUB_TOKEN }}
          HA1_VERSION_SOURCE: 'ci'
      - name: 更新 Nightly
        uses: softprops/action-gh-release@v3

#        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
#      if: github.event_name == 'workflow_dispatch'
        with:
          tag_name: build-${{ github.run_number }}
          name: "Nightly Build#${{ github.run_number }}"
          prerelease: true
          overwrite: true
          body: |
            ### 构建信息
            - **安卓壳分支**: `${{ github.event.inputs.branch }}`
            - **子模块分支**: `easy`
            - **构建时间**: ${{ github.event.repository.updated_at }}
            Commit: ${{ github.sha }}
          files: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/apk/debug/*.apk
            **/*.apk
#          tag_name: debug-build-${{ github.run_number }}
#          name: Debug Build ${{ github.run_number }}
   #       body: |
   #         包含构建目录下的所有 APK 文件。
            
          draft: true
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Upload APK Zip
#        uses: actions/upload-artifact@v4
#        with:
#          name: app-release-${{ github.sha }}
#          path: app/build/outputs/apk/release/Han1meViewer-v*.apk
